#spring:
#  datasource:
#    username: root
#    password: root
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/trade?useSSL=falsespring:
  thymeleaf:
    cache: false

  spring:
    banner:
      location: banner.txt
